# _config.yml
title: "A/Prof Sarvnaz Karimi"
email: sarvnaz.karimi@monash.edu
description: >
  Associate Professor, Monash University
baseurl: ""
url: "https://skarimi.github.io"
github_username: sarvnazkarimi

remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty
future: true
include:
  - _pages
  - _data

author:
  name: A/Prof Sarvnaz Karimi
  avatar: /images/Sarvnaz.jpg
  bio: Principal Research Scientist at CSIRO Data61
  location: Clayton, VIC, Australia
  uri: https://people.csiro.au/K/S/Sarvnaz-Karimi
  email: sarvnaz.karimi@csiro.au
  linkedin: https://www.linkedin.com/in/sarvnaz-karimi-phd-64ab491/
  scholar: https://goo.gl/KoTmwz

interests:
  - Natural Language Processing
  - Information Retrieval
  - Biomedical Text Mining
  - Digital Health
  - NLP for Climate Science & Agriculture
  - Large Language Models for Science

google_analytics:
